# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog_post', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(),
        ),
    ]
